- hosts: all              # Specifies which host IP addresses to apply the deployment & service  - ansible will execute this playbook
  become: true
  tasks: 
     - name: delete old deployment
       command: kubectl delete -f /home/ubuntu/Deployment.yml
       ignore_errors: yes
     - name: delete old service
       command: kubectl delete -f /home/ubuntu/Service.yml
       ignore_errors: yes
     - name: create new deployment
       command: kubectl apply -f /home/ubuntu/Deployment.yml
       ignore_errors: yes
     - name: create new service
       command: kubectl apply -f /home/ubuntu/Service.yml
       ignore_errors: yes
