kind: Deployment
apiVersion: apps/v1
metadata:
   name: demo-devops
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: demo-devops
   template:
      metadata:
        labels:
          app: demo-devops
      spec:
       containers:
        - name: demo-devops
          image: uokereh/pipeline-1
          imagePullPolicy: Always
          ports:
          - containerPort: 80