kind: Service                             
apiVersion: v1
metadata:
  name: demo-devops
  labels:
    app: demo-devops
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: demo-devops                    
  type: LoadBalancer                   
